sched: android: Fix build error with arm-eabi-4.8
commit 029e7b086ea8 "sched: Introduce energy data structures"
defines sched_group_energy struct.

this commit fixes build error/warnings for modules which are still dependent
on arm-eabi-4.8

build error:
include/linux/sched.h:1164:42: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
const struct sched_group_energy * const(*sched_domain_energy_f)(int cpu);
                                          ^
cc1: all warnings being treated as errors
make[1]: *** [kbuild] Error 2
make: *** [build] Error 2

Change-Id: I6396ae07382d4e9e6733307df7e63dde3786dbc4
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>